services:
  app:
    image: node-app
    ports:
      - 8080:8080
  db:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    volumes:
      - server-db:/var/lib/postgresql/data

volumes:
  server-db:
    external: true